---
title: "SIAD"
---


Bienvenidos a SIAD,

En el Semillero de Investigación Análisis de Datos (SIAD), nos dedicamos a  fomentar el aprendizaje y la innovación en el campo del análisis de datos. Nuestra misión es capacitar a estudiantes y profesionales para que desarrollen habilidades avanzadas en el análisis de información, utilizando técnicas y herramientas de vanguardia.

En SIAD, creemos que el análisis de datos es fundamental para la toma de decisiones informadas en cualquier sector. Por ello, ofrecemos una plataforma colaborativa donde los miembros pueden participar en proyectos de investigación, asistir a talleres y seminarios, y compartir conocimientos con una comunidad apasionada por los datos.

<br><br><br>

Nuestras Redes Sociales

 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
        <style>
          .social-icons {
              display: flex;
              justify-content: ; /* Centra los íconos horizontalmente */
              margin: 10px 0; /* Espacio arriba y abajo de los íconos, puedes ajustar el valor */
          }
          .social-icons a {
              margin: 0 5px; /* ajustar la distancia entre los iconos*/
          }
          .social-icons i {
              color: black; /* Color de los íconos */
              font-size: 30px; /* Tamaño de los íconos */
          }
        </style>
        
<div class="social-icons">
  <a href="https://www.instagram.com/siadata_unimag?igsh=MWZ1YzF4YjhoZWNlaw==" target="_blank">
      <i class="fa-brands fa-instagram"></i>
  </a>
  <a href="https://x.com/siadata_unimag?s=2" target="_blank">
      <i class="fa-brands fa-twitter"></i>
  </a>
  <a href="1" target="_blank">
      <i class="fa-brands fa-linkedin"></i>
  </a>
</div>
&copy; 2024 SIAD. Todos los derechos reservados.
